### ISSUE TITLE
FileManager: get selected files

### ISSUE THREAD

**Issue by therox** [DevExpress/DevExtreme#10322]
I'm developing upload/download module and have a question: Is there any way to get list of selected files/folders from FileManager(CTP) widget? If no, will this functionality be in release?

Using 19.2.2-beta with angular bindings.

**Comment by vladkovl** [comment]
Starting with v19.2.2-beta, you can use the [fileManager.getSelectedItems(](https://js.devexpress.com/Documentation/19_2/ApiReference/UI_Widgets/dxFileManager/Methods/#getSelectedItems)) method to get an array of selected files and folders. See how to use this method in the [Toolbar and Context Menu](https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileManager/UICustomization/jQuery/Light/) demo. I recommend you use the 19.2.3 version for this widget, because the format of objects, which is returned by this method, differs from that of the beta version.
