### ISSUE TITLE
Java Script - dxDataGrid export to PDF

### ISSUE THREAD

**Issue by borellaster** [DevExpress/DevExtreme#10927]
I would like to know if this feature will be implemented. Once read that this would be being implemented in version 19.2.

Thanks

**Comment by hakimio** [comment]
It was never on the roadmap for 19.2, not sure where you got the idea that they planned to implement it for 19.2. 
You'll be able to see what's the plan for 20.1 on their [Roadmap page](https://js.devexpress.com/Roadmap/) sometime soon.

**Comment by borellaster** [comment]
Hello

Please read by yourself - Roadmap Last updated: 15-MARCH-2019

Menu - DataExport

Export to PDF - Expected in 19.2
We plan to offer a PDF export option in our DataGrid and Pivot Grid.

Here I got the idea.
https://web.archive.org/web/20190330074105/https://js.devexpress.com/Roadmap/

Thanks

**Comment by IgnatovDan** [comment]
We've addressed this question in the comments to [our recent blog-post](https://community.devexpress.com/blogs/javascript/archive/2019/12/10/devextreme-angular-react-vue-jquery-roadmap-2020-your-vote-counts.aspx). Let me re-post the answer here:

You are right, we mentioned this feature in our final 2019 Roadmap blog post (it was considered for 19.2 or later). As you may know, we are currently working on a new Export to Excel API (it received more votes than PDF export - 73% vs 48% of the votes). PDF support is the next item in our DataGrid export feature list. In order to make Excel/PDF Export support possible, we refactored significant portions of our codebase last year. All of this has taken more time than was expected... please accept my apologies.
