### ISSUE TITLE
Version 19.2.5 is available in yarnpkg but not in Github

### ISSUE THREAD

**Issue by pedrofurtado** [DevExpress/DevExtreme#11250]
@BingoRUS @babich-a 
The version 19.2.5 is already available in yarnpkg ( https://unpkg.com/browse/devextreme@19.2.5/ ), but not in Github repo yet 👍

**Comment by hakimio** [comment]
https://github.com/DevExpress/DevExtreme/releases/tag/19.2.5

**Comment by BingoRUS** [comment]
Hello @pedrofurtado and thank you for using DevExtreme!
The latest release v19.2.5 is available since December 18. Usually, we publish npm and NuGet packages, make the library available via CDN, add a GitHub release, update documentation and demos all at once. But sometimes it takes more time for some reason.
I've added the v19.2.5 to GitHub today, you can use the link @hakimio provided.

**Comment by pedrofurtado** [comment]
@BingoRUS @hakimio Thanks for feedback and explanation! Merry christmas for all in Devextreme team 🤝 🎅
