### ISSUE TITLE
Jalali calendar in dxdatebox devextreme

### ISSUE THREAD

**Issue by yeganesalami** [DevExpress/DevExtreme#11306]
Hi . How can i change globlizayion of my dxdatebox from gregorian to jalali ? 
I know that i have to use globlization.js and cldr.js and dependencies but still when i am using dxdatebox it is not working and says your date.js is not supporting jullian calendar
Is there any when that i change my dxdatebox to julian? 
Thanks for your attention

**Comment by San4es** [comment]
Hi all,

I have prepared a simple example demonstrating dxCalendar and dxDateBox in the 'fa-IR' culture:
[https://codepen.io/San4esZ/pen/RwPmQeY?editors=1010](https://codepen.io/San4esZ/pen/RwPmQeY?editors=1010)

Please let us know if it meets your requirements.

**Comment by shahabfar** [comment]
That's great. you can use:
شنبه 1ش 2ش 3ش 4ش 5ش جمعه
instead of a full rewrite of daily names in order to occupy low spaces.

BTW do you have any solution to use the filtering functionality of Jalali date in some controls such as dxGrid?

**Comment by San4es** [comment]
Hi @shahabfar.

>That's great. you can use:
شنبه 1ش 2ش 3ش 4ش 5ش جمعه
instead of a full rewrite of daily names in order to occupy low spaces.

Thank you for your feedback and suggestion!


>BTW do you have any solution to use the filtering functionality of Jalali date in some controls such as dxGrid?

Our localization mechanism is the same in all widgets. See the [Localization](https://js.devexpress.com/Documentation/Guide/Common/Localization/) topic and the [Localization](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Localization/) section in our technical demos.

I'm closing this thread. If you have any further questions, feel free to create new [GitHub issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).

**Comment by afruzan** [comment]
Hi @San4es . the issue is about persian calendar (jalali calendar) not about translating weekday and month names to persian. your example only translates gregorian calendar. see https://en.wikipedia.org/wiki/Solar_Hijri_calendar.

any one has any solution?

**Comment by afruzan** [comment]
it seems devextreme-react-scheduler supports persian calendar. see https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-ld6e3

but what about dxDateBox and dxCalendar?

**Comment by afruzan** [comment]
I forked another example and set local to 'fa'. https://codesandbox.io/s/formatting-devextreme-date-box-forked-q4l9k
in this example persian calendar comes but has many bugs. Today button works invalid. year view and years number are invalid...

thanks.
