### ISSUE TITLE
DX Data Grid Multi-Row-Header (Bands) Export to Excel alignment

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#11313]
<!--
### Steps to Reproduce:

1.  Dx Data Grid load data with multi-row-header
    With export to excel using excel JS, Top Header Row (merged cell) column alignment to be centred
 

### Results You Received:
1.Unable to find multi-row column header alignment property. 

### Results You Expected:
1. Need Each multi row column header alignment

### Environment Details:

![Issue](https://user-images.githubusercontent.com/47413890/71475953-b8976380-2808-11ea-9cd0-7cdf6b08b864.png)

**Comment by IgnatovDan** [comment]
I am afraid I cannot give you any advice without researching your project.
Would you please send us your project, so that we can assist you further? This will greatly help us understand how to help you with this task.

See also: 
- [T810780 - DataGrid exports columns with the offset if the allowExporting option is set to false for a column under a band column](https://supportcenter.devexpress.com/internal/ticket/details/T810780)
- [T847294 - Export multi row headers from DXGrid to excel](https://supportcenter.devexpress.com/internal/ticket/details/T847294)
