### ISSUE TITLE
TreeView in search not show childs

### ISSUE THREAD

**Issue by HASSANDL** [DevExpress/DevExtreme#11376]
TreeView not show childs after search.

![image](https://user-images.githubusercontent.com/22093903/71613861-e5a79580-2bbd-11ea-82f6-28f71b6bb4db.png)

**Comment by novsstation** [comment]
Hi HASSANDL,

The TreeView displays only found nodes and their parents when search is used. This behavior is by design.

If you need to retrieve child nodes for nodes that do not match search criteria, please refer to this  [ticket](https://www.devexpress.com/Support/Center/Question/Details/T647258/treeview-when-select-a-node-and-node-s-children-become-empty-array-after-filter) for more information.

Additionally, you can use the [TreeList widget](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/Overview/jQuery/Light/) and [filter mode](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/FilterModes/jQuery/Light/) option to display the entire tree branch.
