### ISSUE TITLE
dxGantt v0.0.29 - item is not repainting after change dates

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#11940]
Hi, 

after update dxGantt to v0.0.29 after change dates in Gantt diagram  the item is not filled with color (devExtreme 19.2.7-build-20036-0311), but the border is visible on mouse hover:

![gantt_bug](https://user-images.githubusercontent.com/13969777/74125239-c7ce4700-4be5-11ea-8534-dfd352d9e254.png)

**Comment by natashaash** [comment]
Hello,
I was not able to reproduce this behavior using [this build](https://www.npmjs.com/package/devextreme/v/19.2.7-build-20036-0311).
The issue can relate to an incorrect update process which we described in the [Gantt v0.0.27 error](https://github.com/DevExpress/DevExtreme/issues/10883) thread. Did you upgrade the whole DevExtreme package?
It can also occur if CSS files of an older version are cached in your browser. I suggest that you try to clear your cache and test this behavior again.
If this does not help, please provide additional information about your scenario so that I can reproduce the issue.

**Comment by Bykiev** [comment]
@natashaash, hello!
Yes, I've updated the whole DevExtreme package on version 19.2.7-build-20036-0311 and it requires devexpress-gantt 0.0.29. I'll try to prepare a runnable demo.

**Comment by Bykiev** [comment]
@natashaash, unfortunately, I can't reproduce this issue on codepen, but when I collapse rows smth cause gantt repaint and everything looking good until I'll change dates again...

**Comment by natashaash** [comment]
Hello,
To be able to determine the cause of this behavior, I need to replicate it on my side. Currently, your Gantt's settings and other details of your scenario are not clear, so, my attempts to replicate the issue are not efficient. Please provide Gantt settings, your project code, or a link to the deployed problematic page. It may be more appropriate to continue this discussion in our [Support Center](https://www.devexpress.com/support/center/question/create). This will allow us to provide faster replays. I will do my best to help you.
