### ISSUE TITLE
TreeList - autoExpandAll option only works on initial instance create not clear data and setting data again

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#12170]
Tested with versions 18.2.8 through 19.2.6. When create a new instance of TreeList and setting the option of `autoExpandAll` and providing data during this instance create the resulting rows are rendered with the nodes all expanded as expected.

If later you do a `treeListInstance.option('dataSource', []);` and `treeListInstance.option('dataSource', someData);` where `someData` is the new hierarchy of data to display, none of the rows that have children are expanded.

I would expect behavior to be that changing the dataSource would still honor the option setting and therefore expand the rows.

Also, don't see an method that does `expandAll` or opposite of `collapseAll`?

**Comment by genachka** [comment]
@Alyar666 @vconst or someone from DevExpress - would appreciate assistance / response?

**Comment by onebalaban** [comment]
Hello,

> none of the rows that have children are expanded

We discussed a similar issue in this ticket: [TreeList - autoExpandAll not working if dataSource that represents an array of items is changed at runtime](https://supportcenter.devexpress.com/ticket/details/t705518/treelist-autoexpandall-not-working-if-datasource-that-represents-an-array-of-items-is). I suggest you use Nikolay's solution from that ticket.

>Also, don't see an method that does expandAll or opposite of collapseAll?

dxTreeList doesn't have these methods. Since the widget may use a remote data source, each expand / collapse operation can take time. You can use the [expandRow](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeList/Methods/#expandRowkey) method in a loop to expand all rows.

See also:
[TreeList - How to expand several rows in a loop](https://supportcenter.devexpress.com/ticket/details/t812049/treelist-how-to-expand-several-rows-in-loop)
