### ISSUE TITLE
[Need Help] Is it possible to save the state of groupedRows in Datagrid

### ISSUE THREAD

**Issue by francesco-clementi** [DevExpress/DevExtreme#12987]
Hi,
I've a Datagrid widget in a React App with grouped rows.
Everytime that is necessary a data reload, datagrid loose the rows grouped. 

Is it possible to save the state of groupRows such as State Storing?

**Comment by onebalaban** [comment]
Hello,

State storing supports row groups - see this demo: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/StatePersistence/React/Light/

If you faced issues with this approach, please submit a ticket to our Support Center and attach a simple project demonstrating the issue so that we can research it.

Regards,
Romeo
