### ISSUE TITLE
calculateSortValue don't working

### ISSUE THREAD

**Issue by luweiymy** [DevExpress/DevExtreme#13633]
### Steps to Reproduce:

1. copy form API about calculateSortValue 
2. <dxi-column dataField="passengerCountVariance" [allowFiltering]="true" sortOrder="asc" [calculateSortValue]="customSortingFunction" 
     [caption]="'uplMissingTktRevenueEstimates_passengerCountVariance' | araf_translate">

3. customSortingFunction(rowData) {
 
    console.log(rowData);

  return rowData.passengerCountVariance;
  }

### Results You Received:

![image](https://user-images.githubusercontent.com/6321099/86107427-648d7480-baf4-11ea-8215-fa21a7a679ee.png)

### Results You Expected:
![image](https://user-images.githubusercontent.com/6321099/86107467-75d68100-baf4-11ea-9638-7c1efc451792.png)

**Comment by MikeVitik** [comment]
I checked your images and noticed that the data in the result you receive and the result you expect is the same. 
Please describe your scenario in greater detail. In addition, create a simple runnable project demonstrating the problem so that I can examine it. You can modify and fork a demo from our [Widgets Gallery](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid)

**Comment by luweiymy** [comment]
> I checked your images and noticed that the data in the result you receive and the result you expect is the same.
> Please describe your scenario in greater detail. In addition, create a simple runnable project demonstrating the problem so that I can examine it. You can modify and fork a demo from our [Widgets Gallery](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid)

Results My Received:[{"desc","false"}]
Results My Expected:[{"selector":"datafieldname","desc","false"}]

**Comment by luweiymy** [comment]
> > I checked your images and noticed that the data in the result you receive and the result you expect is the same.
> > Please describe your scenario in greater detail. In addition, create a simple runnable project demonstrating the problem so that I can examine it. You can modify and fork a demo from our [Widgets Gallery](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid)
> 
> Results My Received:[{"desc","false"}]
> Results My Expected:[{"selector":"datafieldname","desc","false"}]

And step3 no print results in the console panel

**Comment by luweiymy** [comment]
I modify and fork a demo from  Widgets Gallery, mock data is no problem,but remotion data has.

**Comment by MikeVitik** [comment]
Hi.
I suppose you use a grid with an active remoteOperation as shows in this [sample](https://codepen.io/vconst/pen/jOWYxVQ).

If remoteOperation is active for sorting, the calculateSortValue property can be initialized only by a string, not a function because it's impossible to serialize a function into a request string. So you need to use a string for calculateSortValue.
If it's not suitable for your scenario, please share more information.

**Comment by luweiymy** [comment]
Yes, you are right.But I want to sort absolute values.
If  I  use a string for calculateSortValue, can you help me  how to realize absolute value sorting？

**Comment by MikeVitik** [comment]
Hi.
General solution is to implement the calculateSortValue logic on the server-side.
For more specific assistance, please share more information about your server-side and what exactly your calculateSortValue logic does.
