### ISSUE TITLE
Devexpress js is not working in windows 7

### ISSUE THREAD

**Issue by MeNarayan** [DevExpress/DevExtreme#14473]
Dear sir/madam.

I am computer teacher from east Asia.

not a days I am facing an issue in windows 7. Not only in single computer in several computers.

I included the Clipboard-File-1.png here.
![Clipboard-File-1](https://user-images.githubusercontent.com/8360811/92289940-118bcf80-ef32-11ea-84b8-f78eccfe549f.png)

In SSL certificate there we can view the certificate from godady. But i don't think devexpress uses the SSL from Godady.

Is this our problem or any other ?

Thank you.

Narayan Nyaupane

**Comment by hakimio** [comment]
The certificate is valid.
Most likely the issue is that your Windows installation is missing some Trusted Root Authority certificates.
Check the following links to see how you can install them.
https://community.spiceworks.com/topic/584022-missing-or-invalid-root-certificates-on-windows-7-64bit
https://www.tecklyfe.com/restore-missing-invalid-root-certificates-windows/
