### ISSUE TITLE
E1059 - All column names must be different

### ISSUE THREAD

**Issue by bobskigit** [DevExpress/DevExtreme#14592]
I've updated to the current alpha version of 20.2. I now get console errors about column names must be different, this did not happen in 20.1.

![image](https://user-images.githubusercontent.com/4225690/93199180-f8f79280-f745-11ea-84b4-0e6b0f2a9973.png)

**Comment by artem-kurchenko** [comment]
Hi @bobskigit,

The issue is unknown to us. Could you please attach your DataGrid configuration for further examination?

**Comment by bobskigit** [comment]
**This works with no errors in 20.1** but in 20.2 it gives the error


  <dx-data-grid class="dx-theme-border-color" [dataSource]="event$ | async" [(selectedRowKeys)]="selectedRows"
    (onSelectionChanged)="selectedChanged($event)" keyExpr="id" >
    <dxo-header-filter
        [visible]="true"></dxo-header-filter>
        <dxo-group-panel [visible]="true"></dxo-group-panel>
        <dxo-summary>
          <dxi-group-item
              column="id"
              summaryType="count"
              displayFormat="{0} items">
          </dxi-group-item>
          </dxo-summary>
    <dxi-column dataField="id" caption="Ad Server Id" dataType="string">
    </dxi-column>
    <dxi-column dataField="eventDateTime" caption="From" dataType="date" [format]="{ type: 'shortDate' }">
    </dxi-column>
    <dxi-column dataField="eventDateTime" caption="Time" dataType="date" [format]="{ type: 'longTime' }">
    </dxi-column>
    <dxi-column dataField="operatorName" [caption]="'Generic.operatorName' | translate" dataType="string">
    </dxi-column>
    <dxi-column dataField="assetId" caption="Programme Ref" dataType="string">
    </dxi-column>
    <dxi-column dataField="adId" caption="Media Ref" dataType="string">
    </dxi-column>
    <dxi-column dataField="channelName" [caption]="'Generic.channelName' | translate" dataType="string">
    </dxi-column>
    <dxi-column dataField="uniqueHandle" caption="Unique Ref" dataType="string">
    </dxi-column>
    <dxi-column caption="User Agent">
    <dxi-column caption="OS" dataField="operatingSystem" [hidingPriority]="0">
      ></dxi-column>
      <dxi-column caption="Browser" dataField="browser" [hidingPriority]="0">
        ></dxi-column>
        <dxi-column caption="Device" dataField="device" [hidingPriority]="0">
          ></dxi-column>
      </dxi-column>
  </dx-data-grid>

**Comment by NickMitrokhin** [comment]
Hi,

In v20.2, DataGrid requires unique names for columns. Column names are generated based on the [dataField](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#dataField) option. In your case, two columns have the same data field "eventDateTime". Therefore, the [name](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#name) option of these columns will have the same value. To resolve the issue, set the **name** option of columns that have duplicated **dataField** values to unique values. For instance:

```html
<dxi-column dataField="eventDateTime" name="shortDateTime" caption="From" dataType="date" [format]="{ type: 'shortDate' }">
<dxi-column dataField="eventDateTime" name="longDateTime" caption="Time" dataType="date" [format]="{ type: 'longTime' }">
```

Since v20.2 is not officially released, this information is not added to our documentation. Moreover, we will create the corresponding breaking change for this behavior.
