### ISSUE TITLE
Angular DevExtreme: Pivot Grid - customSave function is triggered after component init

### ISSUE THREAD

**Issue by akuchyk** [DevExpress/DevExtreme#14660]
I try to store the current state of PivotGrid and use the 'custom' storage type(according [documentation](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxPivotGrid/Configuration/stateStoring/) ), please see my [example](https://codesandbox.io/s/state-persistence-devextreme-pivot-grid-z8bgj?file=/src/app/app.component.ts) . But the first time after the component is initialized, the customSave function is triggered. How I can avoid it? Many thanks!

**Comment by novsstation** [comment]
Hi,

Currently, this behavior is expected.
In a general case, after the state is loaded, it is possible to change it in code.
That's why, these changes must also be saved.

So, to prevent the state from being saved when it's not necessary, you can introduce an additional variable:

```ts
export class AppComponent {
  skipFirstSaveEvent: boolean = true;
  ...
  saveState = (state) => {
    if (this.skipFirstSaveEvent) {
      this.skipFirstSaveEvent = false;
    } else {
      console.log("Save");
      console.log(state);
    }
  };
```

I modified [your sample](https://codesandbox.io/s/state-persistence-devextreme-pivot-grid-forked-do4zo?file=/src/app/app.component.ts:3134-3311) to illustrate this approach in action.
Please check it and let me know if this meets your requirements.

**Comment by akuchyk** [comment]
Thanks!
