### ISSUE TITLE
Chart annotations lines adding goal 

### ISSUE THREAD

**Issue by adardesign** [DevExpress/DevExtreme#14981]
Using the chart,  I am trying to implement the following:

1. click on the value axis (could be done via [14184](https://github.com/DevExpress/DevExtreme/issues/14184)) 
2. add an annotation in the form of a goal  
3. ability to drag the goal line up and down and show the value  until the user chooses to save at the new value

![Screen Shot 2020-10-19 at 10 56 36 PM](https://user-images.githubusercontent.com/23543/96534987-df72ca80-125e-11eb-861b-047403a08853.jpg)

**Comment by alexanderPolosatov** [comment]
Hi,
I see that we are discussing the same inquiry in the following ticket: [T940859](https://supportcenter.devexpress.com/ticket/details/t940859/no-click-handler-for-onvalueaxisclick-similar-as-onargumentaxisclick). Let's continue there. Please feel free to leave a comment in that ticket if something remains unclear. We will be happy to help you.

We track all the questions we receive and answer them in order so that we don't miss any. Please do not create separate tickets/GitHub issues for the questions you already addressed. This will allow us to process all your inquiries in the most efficient way.
