### ISSUE TITLE
dxDateBox.dateSerializationFormat doesn't work with initial value

### ISSUE THREAD

**Issue by meancrazy** [DevExpress/DevExtreme#1536]
### Steps to Reproduce:
1. Create dxForm with dxDateBox, set dateSerializationFormat and provide initial value:
```js
$("#Form").dxForm({
    "colCount": 1,
    "width": 300.0,
    "items": [{
        "itemType": "simple",
        "dataField": "Date",
        "editorOptions": {
            "width": 200.0,
            "displayFormat": "shortDate",
            "dateSerializationFormat": "yyyy-MM-dd"
        },
        "editorType": "dxDateBox",
        "label": {
            "text": "Дата отчёта"
        }
    }],
    "formData": {
        "Date": new Date(2017,9,12)
    }
});
```
2. Run at js console following code:
```js
$('#Form').dxForm('instance').option('formData')
```
3. Then select another date in dxDateBox and run code again:

### Results You Received:
At first run you get a js date object: `{Date: Thu Oct 12 2017 00:00:00 GMT+0300 (Russia Standard Time)}`
At second run you get formatted string: `{Date: "2017-10-12"}`

### Results You Expected:
Each time we will should receive a formatted string.

### Environment Details:
```
Devextreme 17.1.6
Chrome 61.0.3163.100
```

**Comment by DokaRus** [comment]
Hi,
It's expected behavior. `dateSerializationFormat` specifies a value's format obtained as a result of UI interaction (mainly it happens case when a widget doesn't have an initial value). If you set the initial value or change the current value via API like `dateBox.option("value", new Date(2017, 7, 7))` - the value isn't changed to `dateSerializationFormat`, because it will raise an unexpected `valueChanged` event.
I see that the ["value"](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDateBox/Configuration/#value) and ["dateSerializationFormat"](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDateBox/Configuration/#dateSerializationFormat) documentation topics don't describe this case, so we'll update our documentation to avoid this misunderstanding.

**Comment by meancrazy** [comment]
Thanks!
So I found that it fixed by setting value as formatted string:
```js
"formData": {
        "Date": "2017-10-12"
    }
```
