### ISSUE TITLE
ContextMenu in v >= 20.2.3 requires quill

### ISSUE THREAD

**Issue by QuentinLuc** [DevExpress/DevExtreme#15604]
### Steps to Reproduce:

1. Import the ContextMenu from 'devextreme-react/context-menu'
2. Upgrade Use devextreme and devextreme-react  from 20.1.9 to >= 20.2.3

### Results You Received:

Since this version, I've go the following error:
![image](https://user-images.githubusercontent.com/5237095/101479333-4f91f880-3952-11eb-9219-efe74426a6b2.png)

Is there something particular that I should do?

#### Packages and configuration
* webpack 5
* "devextreme": "20.2.0",
* "devextreme-react": "20.2.0",
* "react": "^16.13.0",
* "react-dom": "^16.13.0",

**Comment by SomeoneIsWorking** [comment]
I got the error to go away by downgrading to webpack 4

**Comment by LexDX** [comment]
Hi @QuentinLuc, @needo2,

We are not aware of this issue. Could you please prepare a sample project that reproduces the issue, so we can analyze and debug it locally? I look forward to hearing from you.

**Comment by SomeoneIsWorking** [comment]
[hey.zip](https://github.com/DevExpress/DevExtreme/files/5723817/hey.zip)

Sample project with webpack 5
I encountered this when trying to upgrade a project that was created from an older template that doesn't use vue-cli
The error is `Cannot read property 'call' of undefined` if imported directly or  `__webpack_require__ is not defined` if it was imported with async code splitting via webpack `import(module)` function

**Comment by LexDX** [comment]
Thank you for the sample, @needo2. I checked it and found that we are already researching this issue in the context of this report: [HtmlEditor - The " __webpack_require__ => Uncaught TypeError: Cannot read property 'call' of undefined" error occurs when an application with the control is built with Webpack 5 and run in the browser](https://supportcenter.devexpress.com/ticket/details/t958647/htmleditor-the-webpack-require-uncaught-typeerror-cannot-read-property-call-of-undefined). Please stay tuned to this ticket for updates.

As for the ContextMenu issue, its cause is still unclear. @QuentinLuc, I will appreciate it if you share a sample project that reproduces it so that we can research it further.

**Comment by LexDX** [comment]
Hi @needo2 , @QuentinLuc,

We fixed this issue and published a new minor version of the DevExtreme-Quill library. Please update DevExtreme-Quill to the latest version to resolve the issue. 
Feel free to reopen this issue if you have any problems.
