### ISSUE TITLE
DataGrid fullScreen - dxSelectBox item is not visible when fullScreen in DataGrid

### ISSUE THREAD

**Issue by duongdo-coder-710z** [DevExpress/DevExtreme#15616]
Hi everyone! I am using Angular 6 with Devextreme version 19.2.10 library. When I using dxSelectbox in normal mode, the data still show when I click the dropdown button but when I switch to fullscreen mode, nothing happens when I click the dropdown button, so I can't see and choose the option. Can you help me solve this problem? Thank you.

**Comment by NickMitrokhin** [comment]
Hi,

The issue is not clear. Would you please clarify what "fullscreen mode" you are talking about? It would be great if you modify [this](https://codesandbox.io/s/row-editing-and-editing-events-devextreme-data-grid-forked-96vu6) example to show the issue.

Note that 19.2 is deprecated and we do not maintain it anymore. I recommend that you upgrade DevExtreme to the most recent version: 20.2.4.

**Comment by NickMitrokhin** [comment]
This issue was closed due to inactivity. If you found a bug or have a question about our product, [create a new issue](https://github.com/DevExpress/DevExtreme/issues) on GitHub or submit a ticket in our [Support Center](https://www.devexpress.com/Support/Center/).
