### ISSUE TITLE
ODataStore errorHandler does not support all httpStatuses

### ISSUE THREAD

**Issue by dhlukhatarenka** [DevExpress/DevExtreme#15945]
[ODataStore errorHandler](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/ODataStore/Configuration/#errorHandler) does not support all httpStatuses:
When happens error with status code 414 (URI Too Long) httpStatus contains 0 and error.message "Unspecified network error".

**Comment by onebalaban** [comment]
Hello,

We return such an error message if the status code is less than 400: https://github.com/DevExpress/DevExtreme/blob/21_1/js/data/utils.js#L78

Could you please elaborate on the issue and describe how we can reproduce it? Then, we will research it further.

**Comment by dhlukhatarenka** [comment]
When OData URL length more than 8192 (in my case in chrome) I'm getting httpStatus in errorHandler equals '0', but in browser I clearly see 414. 
For example for unauthorized error status is right.

**Comment by artem-kurchenko** [comment]
Hi @dhlukhatarenka 

Could you share what OData service type you have? I tested existing public services but they throw the 400 and 404 errors in such scenarios: https://codepen.io/ArtemDevExpress/pen/LYbbxgj?editors=1010

It would be nice if you share what server-side library and data provider you use so we can take this information on further development.

**Comment by dhlukhatarenka** [comment]
Hi @artem-kurchenko

I'm using netcoreapp3.1, but I think it is not important.
400 and 404 still wrong status code for error when your URL very long. Right status is **414 URI Too Long**
Unfortunately I can't share anything now.

**Comment by artem-kurchenko** [comment]
Hi @dhlukhatarenka

Thank you for the explanation. I tested an ASP.NET Core app with an OData controller and found that it throws this error with the 404 status. The "414 URI Too Long" message is a part of the response body, but ASP.NET Core applications send a message as well as the whole HTML page with a lot of markup and styles.

![](https://user-images.githubusercontent.com/22076961/114991003-c790a200-9ea1-11eb-8556-acee8ed35add.png)

ODataStore was designed to parse errors that appear while an OData library works with a query (these errors usually come in the form of `{ httpStatus: ... , message: ..... }`).

This particular error appears at the application level and raised before Controller actions are executed. Our stores don't have advanced logic to parse these pages. That's why you get the "Unspecified network error" message instead of relevant content.
In this case, you can write a middleware that will send a plain object to the client side so our component can obtain a relevant message.
