### ISSUE TITLE
Safari: Fields dragging doesn't work properly in PivotGrid Field Chooser

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#17366]
### Steps to Reproduce:

1. Create PivotGrid Field Chooser (bug reproduced on demo page: https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/StandaloneFieldChooser/React/Light/)
2. Be sure that field area has enough fields (field area should have scrolling).
3. Try to drag field from this field area to another.
![image](https://user-images.githubusercontent.com/1198848/117125185-e055ee80-ada1-11eb-8ee9-c802b0d8c263.png)

### Results You Received:
Field doesn't move. Field starts moving only after dragging it to left or to right.

### Results You Expected:
Field is moving.

### Environment Details:
Safari
DevExtreme: 20.2.6, 20.2.7

---

Possible workaround: change scrolling to non native. But there is no configuration for making it for PivotGrid Field Chooser.
https://github.com/DevExpress/DevExtreme/blob/ecd0cec51f0c68e70ed2034a8f2a09a1606d43ea/js/ui/pivot_grid/ui.pivot_grid.field_chooser.js#L575

It is possible for changing default scrolling:
```js
  dxScrollable.defaultOptions({
    device: { deviceType: 'desktop' },
    options: {
      showScrollbar: 'always',
      useNative: false,
    },
  })
```

But it is not suitable for me because I want to have native scrolling on other places (for example programming scroll can't handle touchpad horizontal gestures).

**Comment by Semigradsky** [comment]
Some activity

**Comment by novsstation** [comment]
Hi,

Please pardon such a long delay in our response.

> Field doesn't move. Field starts moving only after dragging it to left or to right.

This behavior is expected. If drag and drop events were intercepted initially, then scrolling up and down on mobile devices would be quite difficult. That's why the priority was given to scroll events.

> But it is not suitable for me because I want to have native scrolling on other places (for example programming scroll can't handle touchpad horizontal gestures).

If this behavior doesn't meet your requirements, you can change the useNative option for dxScrollable widgets that are located inside the dxFieldChooser:

```js
  <PivotGridFieldChooser
     ...
    onContentReady={this.fieldChouserContentReady} >
          
  fieldChouserContentReady(e) {
    const areas = e.element.querySelectorAll(".dx-scrollable");
    for (var i = 0; i < areas.length; ++i) {
      Scrollable.getInstance(areas[i]).option("useNative", false);
    }
  }          
```

I modified [our demo](https://codesandbox.io/s/qicor) to illustrate this approach.
Should you have any questions, feel free to contact us.
