### ISSUE TITLE
Filter arguments are changed after submitting

### ISSUE THREAD

**Issue by maya-harel** [DevExpress/DevExtreme#20846]
I am working with DevExtreme's `DataGrid` object, using its `FilterPanel`

When creating a filter like this:
![image](https://user-images.githubusercontent.com/24511342/149951626-c67a6c65-0833-421c-bb5c-a903a9e81de4.png)

After hitting send and opening the filter again, it changes:
![image](https://user-images.githubusercontent.com/24511342/149951652-023da51a-d918-4974-9852-8c1e607bb33c.png)
![image](https://user-images.githubusercontent.com/24511342/149951670-4d476fe4-7c1f-42fe-908d-9b04b17df9cf.png)

### Environment Details:
"devextreme": "20.2.6",
 "devextreme-react": "20.2.6"

**Comment by onebalaban** [comment]
Hi,

This behavior is expected. Your filters in the first screenshot mean that your DataGrid should create the following statement: filter by "Health service area" AND "Hospital county" AND one of the conditions specified under the "OR" statement. Since there is only one dataField ("Gender"), the filter representation is simplified to match the applied filter - the "OR" statement is simply not necessary here. If you add more conditions under the "OR" statement, the filter will not be changed. Have a look at the attached screencast

https://user-images.githubusercontent.com/25555034/150788559-51a37616-03e8-4029-81ba-5dfe521846f8.mp4

.
