### ISSUE TITLE
TreeList - Editing Form - Form not extended when the editors extends

### ISSUE THREAD

**Issue by foaudkajj** [DevExpress/DevExtreme#20878]
### Steps to Reproduce:

1. Open the [sandbox](https://eqrl7.csb.app/).
2. Edit the last row of the `TreeList` and add three or four new rows to the `DataGrid` under the `Custom Date Field` label.

### Results You Received:
The save, cancel buttons and some parts of the form are hidden and it is not possible to save the form.

### Results You Expected:
The editing form should extend after adding the new rows.

### Environment Details:
"devextreme": "21.2",
"devextreme-angular": "21.2"

Note: Removing this line fiexes the problem. `<dxo-column-fixing [enabled]="true"></dxo-column-fixing>`

**Comment by onebalaban** [comment]
Hello,

Such issues can occur if custom content is used in templates because TreeList cannot track changes made inside templates.

You can use the `onRowInserted` event handler to resolve the issue:
`  onRowInserted(e) {
    this.treeList.instance.updateDimensions();
  }`

Have a look at the following example: [CodeSandBox](https://codesandbox.io/s/form-editing-devextreme-data-grid-forked-3ml9q?file=/src/app/app.component.ts).
