### ISSUE TITLE
Ошибка в dxSelectBox

### ISSUE THREAD

**Issue by kodermax** [DevExpress/DevExtreme#2392]
Если в форме указать поле dxSelectBox с CustomStore с указанными полями displayExpr и valueExpr,
то будет вызван многократное load у CustomStore
Пример
https://codepen.io/anon/pen/JMpXVz

**Comment by jsdmitry** [comment]
Hi,
 
I researched your example and found out that you are using the displayExpr and the valueExpr options for the dxSelectBox incorrectly. The Name and the Id data fields are not contained in the dxSelectBox's data source. If you use the Employee field as displayExpr and the OrderNumber field - as valueExpr, unnecessary load methods will not will be called.
 
I kindly ask you to write in English, because our other customers can be interested in our answers.

**Comment by kodermax** [comment]
But I have api which contains Id and Name.
And this error is still there.

**Comment by kodermax** [comment]
I had to make a stub
![image](https://user-images.githubusercontent.com/590985/34765912-d1487b28-f603-11e7-9d26-bae599cadac2.png)

**Comment by jsdmitry** [comment]
The [displayExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxSelectBox/Configuration/#displayExpr) and [valueExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxSelectBox/Configuration/#valueExpr) options should provide data fields of SelectBox's data source. 
Please check that Id and Name data fields are contained in your remote data source.

**Comment by AlekseyMartynov** [comment]
Hi there
In order to provide better assistance, we need to better understand the scenario and the issue.

Currently we realize the following:

- The initial CodePen sample contains a misconfigured `dxSelectBox` but according to https://github.com/DevExpress/DevExtreme/issues/2392#issuecomment-356551451 it's not the concern of the ticket.

- From https://github.com/DevExpress/DevExtreme/issues/2392#issuecomment-356551997 we can make the assumption that you don't want to load data unless there is a filter. This is fine if that approach works as expected.

- If data bound to `dxSelectBox` is relatively small and static then I suggest to try [`loadMode="raw"`](https://js.devexpress.com/Documentation/Guide/Data_Layer/Data_Source_Examples/#Custom_Sources/Load_Data_in_Raw_Mode),
 a special mode in which only one fetch is made and the datasource configuration is much simplier:

    ```js
    var orders = new DevExpress.data.CustomStore({
        loadMode: "raw",
        load: function () { 
            var deferred = $.Deferred();       
            $.ajax({ 
                url: "https://js.devexpress.com/Demos/WidgetsGallery/data/orderItems",
                success: function(result) {
                    deferred.resolve(result.items);
                },
                error: function() {
                    deferred.reject("Data Loading Error");
                },
                timeout: 5000
            });    
            return deferred.promise();
        }
    });
    ```

**Comment by kodermax** [comment]
Thank you.
It works.
