### ISSUE TITLE
Changes to columnResizingMode in code is ignored if localstorage is used

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#24818]
### Steps to Reproduce:

1. Use this demo: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/StatePersistence/jQuery/Light/
2. set 
```
columnResizingMode: 'widget',
width: '300px',
```

try to change column's width to make horizontal scrollbar visible - it changes according to `columnResizingMode`

3. set `columnResizingMode: 'nextColumn',`

### Results You Received:

Column resizing mode still using saved in localstorage value for column's width

### Results You Expected:

Change `columnResizingMode` should change column's width according to grid width

### Environment Details:

All DevExtreme versions.

**Comment by AlisherAmonulloev** [comment]
I did not manage to replicate the issue. In the demo you shared, the component does not save the `columnResizingMode` option to the local storage. The following help topic shows the list of options the component saves: [DataGrid - Configuration - stateStoring](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/stateStoring/). If the issue occurs on your side, please submit a support ticket to our Support Center and record a video illustrating the issue so that we can be sure we are reproducing it exactly as you described. You can use the following link to create a ticket: [https://devexpress.com/ask](https://devexpress.com/ask)
