### ISSUE TITLE
Overwriting default DataGrid settings in FileManger (React)

### ISSUE THREAD

**Issue by vyshkant** [DevExpress/DevExtreme#24928]
Currently FileManager React component uses this code to create a grid of shown files:
https://github.com/DevExpress/DevExtreme/blob/7708324f10548e1925a8ae0e1251e52c86a5c9b0/js/ui/file_manager/ui.file_manager.item_list.details.js#L74-L109

As you may see, some part of this properties are just hard-coded in FileManager component, which prevents users from passing their own values to the nested DataGrid component.

My immediate goal is to make FimeManager grid behave as it is shown [in this example of yours](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MultipleRecordSelectionModes/React/Light/): , with **`Show Checkboxes Mode` set to "always"** (I want for the row itself to not be clickable, whereas checkboxes should be shown all the time), which is impossible due to hardcoded values.

Are there any actual problem with allowing this options passing, or I may try and write a PR for this matter?

**Comment by AlisherAmonulloev** [comment]
We do not recommend setting the options of the DataGrid component that is used in the File Manager control because the control handles the DataGrid component's state, and some options specified outside may interfere with how the control interacts with the DataGrid component.
If you are OK with dealing with possible issues that may arise in this scenario, you can access the DataGrid component using the private API. Here is how you can access the instance of the DataGrid component:

```js
fileManagerInstance._itemView._filesView
```

If you have further concerns, please submit a support ticket: [https://devexpress.com/ask](https://devexpress.com/ask).
