### ISSUE TITLE
Not working correctly in iframe

### ISSUE THREAD

**Issue by AKNiazi** [DevExpress/DevExtreme#4454]
I am trying to use devextreme data grid in an iframe. Iframe is created using node vm runInNewContext method. Although, grid is drawn correctly, action can be applied only once. For instance, i can apply sorting only once. When i click somewhere else in the page and then sort again it works for one time again.

Note
1. The same code works fine outside the iframe.
2. Instead of using this npm package, if i use jquery dx.all file. It works fine in iframe as well.

I checked on google Chrome on Ubuntu

**Comment by AlekseyMartynov** [comment]
It's not clear for us how you combine `vm.runInNewContext` with 'Chrome on Ubuntu'.
Please provide more details about the project and frameworks/tools being used.

**Comment by AKNiazi** [comment]
I am modifying [superset](https://github.com/apache/incubator-superset) for an in house project.

This is how [vm.runInNewContext](https://github.com/apache/incubator-superset/blob/master/superset/assets/src/modules/sandbox.js) is being used.

Taking the code in the above link as an example.

I added DevExpress to the context


> const GLOBAL_CONTEXT = {
         console,
         DevExpress,
};


and then called sandboxedEval method with devextreme datagrid initialization code.

**Comment by AlekseyMartynov** [comment]
Can it be that you load both `dx.all.js` and individual DevExtreme modules from the npm package?
We debugged a similar case in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/214#issuecomment-391675919.

Since you are using the global `DevExpress` object, loading `dx.all.js` (or a [custom bundle](https://js.devexpress.com/Documentation/Guide/Common/Modularity/Create_a_Custom_Bundle/)) is a way to go.

**Comment by AKNiazi** [comment]
So when i require jquery in the sandbox.js, many things get fixed. However, drag and drop, scrolling are not working and filter popups does not show in the proper place as popups are appended outside the iframe.

**Comment by AlekseyMartynov** [comment]
> popups are appended outside the iframe.

This is very unusual. It seems that due to peculiarities of `sandboxedEval`, jQuery gets a wrong [context](http://api.jquery.com/jquery/#selector-context).

Luckily jQuery isn't a required dependency [since 17.2](https://community.devexpress.com/blogs/donw/archive/2017/11/09/devextreme-with-and-without-jquery-v17-2.aspx). Try without jQuery. Check [Getting Started](https://github.com/DevExpress/DevExtreme#getting-started) for an example of pure JS widget initialization.

**Comment by AlekseyMartynov** [comment]
**UPDATE**
I see that superset [uses jQuery internally](https://github.com/apache/incubator-superset/search?q=jquery).
Try to include it in `GLOBAL_CONTEXT`:

```js
const GLOBAL_CONTEXT = {
  global.$,
  global.jQuery,
  // . . .
};
```
