### ISSUE TITLE
Zoom in / Zoom out problem

### ISSUE THREAD

**Issue by NorDroN** [DevExpress/DevExtreme#4858]
### Steps to Reproduce:

1. Open https://js.devexpress.com/ 
2. Zoom in / Zoom out

### Results You Received:
<img width="952" alt="screenshot_85" src="https://user-images.githubusercontent.com/5458276/43395812-233e9d8e-9408-11e8-9c9c-ea2edc7cd2c1.png">
<img width="952" alt="screenshot_86" src="https://user-images.githubusercontent.com/5458276/43395899-6a5f57a8-9408-11e8-95b3-65ef1e46d165.png">

**Comment by AlekseyMartynov** [comment]
Possibly related: https://bugs.chromium.org/p/chromium/issues/detail?id=717469

**Comment by NorDroN** [comment]
I think it depends on your styles only.
Of course I understand that your components contain really difficult markup and a lot of styles, but if I use a simple table, I don't see the same behavior.
As you can see on the first image cells in the first column have incorrect height.
Try to add style
```
.dx-datagrid-group-closed,
.dx-datagrid-group-opened {
  height: unset;
}
```

**Comment by AlekseyMartynov** [comment]
Thanks @NorDroN 

/cc @vconst @Alyar666 what do you think about the suggested CSS change?

**Comment by NorDroN** [comment]
If we speak about the second problem, I see that
<img width="952" alt="screenshot_89" src="https://user-images.githubusercontent.com/5458276/43569400-047e29ca-9640-11e8-8681-fa93b6253368.png">

**Comment by Alyar666** [comment]
Hello,

Regarding the first problem. We checked this behavior in the latest Chrome version (v68.0.3440.84) and it works fine there - it appears that the issue is resolved at the Chrome level. I suggest you update your Chrome version to the latest one.

Regarding the second problem. We will process this issue in the context of the following Support Center thread: [dxDataGrid - Row borders are incorrectly displayed after changing zoom](https://www.devexpress.com/Support/Center/Question/Details/T660944)
