### ISSUE TITLE
[18.1.5] Setting grid column's "calculateDisplayValue" config causes filter name to be replaced by a function

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#5176]
### Steps to Reproduce:

1.  Assign "calculateDisplayValue" config to a grid column (function name).
2. Assign "loading" event listener to grid's store which logs loadOptions to console.
3. Try to filter the grid using grid search panel and check the console output.

### Results You Received:
The name of the column which has "calculateDisplayValue" config assigned is replaced by the "calculateDisplayValue" function in "loadOptions.filter" property like shown below:
![filter](https://user-images.githubusercontent.com/768105/44569687-7e810200-a77b-11e8-98cd-f7ec04d8c26a.PNG)

### Results You Expected:
All filters should still have their original names from "dataField" column config in the loadOptions filter.

### Environment Details:
DevExtreme: 18.1.5
devextreme-angular: 18.1.5

**Comment by vconst** [comment]
Hi @hakimio,
 
DataGrid does not support defining **calculateDisplayValue** as a function if **remoteOperations** are enabled. You can find a list of restrictions when operations are remote in the [remoteOperations](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/remoteOperations/) topic. The **calculateDisplayValue** callback is used for filtering and grouping. That's why you see this callback in the loadOptions.filter array.
 
Would you describe why you are using a function in this case? In addition, please post here your implementation for further examination. We'll check for alternative solutions.

**Comment by hakimio** [comment]
Ok, I did not see that restriction. Maybe you should add a note in "calculateDisplayValue" config documentation?

Anyway, my use case was to just format some id ("1234567890" => "123-456-7890"). As a work-around I am using "cellTemplate" now which can accomplish the same but in a different way.

If you don't consider this unexpected behavior to be a bug, feel free to close this one.

**Comment by vconst** [comment]
Yes, we will add a note to the [calculateDisplayValue](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#calculateDisplayValue) documentation. Using cellTemplate is a good solution for your task. Also you can use the [customizeText](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#customizeText) callback to customize text in the cells.
