### ISSUE TITLE
Scheduler - RecurrenceRule not following RFC2445 specification

### ISSUE THREAD

**Issue by gercobrandwijk** [DevExpress/DevExtreme#5900]
The scheduler should follow the RFC2445 specification when it comes to the recurrence rules. At https://js.devexpress.com/Documentation/Guide/Widgets/Scheduler/Appointments/Appointment_Types/#Recurring_Appointments is described that it follows that specification. When you follow that link you will end up here: https://tools.ietf.org/html/rfc2445#section-4.3.10. In that document there is an example of a recurrence rule for "the last work day of the month":

FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1

I copied this into my scheduler appointment, but the scheduler is showing a reucrrence every last work day of the week instead of the month.

### Steps to Reproduce:
See https://codesandbox.io/s/92ll360oqp

### Results You Received:
A recurrence every last work day of the week

### Results You Expected:
A recurrence every last work day of the month

### Environment Details:
DevExtreme 18.1.6

**Comment by artem-kurchenko** [comment]
Hi,
 
Thank you for the detailed report. Currently, Scheduler doesn't support "BYSETPOS". We have plans to improve the built-in Recurrence Rules Editor in our [RoadMap for Scheduler](https://js.devexpress.com/Roadmap/#Scheduler) to support this and other missing recurrence options. We will make an announcement once we have any progress.

**Comment by Jesse-imuzo** [comment]
Hello @artem-kurchenko,

Has there been any movements on "BYSETPOS" or any work arounds?

**Comment by sometimesElen** [comment]
Hello,

Please accept my apologies for the delay. We are working on the recurrences in our Scheduler in the context of the following thread: [Scheduler - Recurring appointments with the BYSETPOS rule are rendered incorrectly](https://supportcenter.devexpress.com/ticket/details/t826136). In this ticket, we collect all cases with the BYSETPOS rule in order to check them when the fix is applied. We will update this thread once we have any news.

If you need any further assistance, I suggest you create a ticket in our [Support Center](https://github.com/DevExpress/DevExtreme/issues/devexpress.com/ask). Our support engineers are always ready to help you with any DevExpress product.
