### ISSUE TITLE
chart export with dark material theme does not show labels/text

### ISSUE THREAD

**Issue by jakehockey10** [DevExpress/DevExtreme#6187]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.2.3
    devextreme-angular version: 18.2.3
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

If I use the code in the example displayed [here](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/ExportSeveralCharts/Angular/MaterialBlueLight/), and I am using a dark material theme, the text in charts are not visible in the image that is exported.  Here is what it looks like in the demo:
![image](https://user-images.githubusercontent.com/1821383/48658187-b30efd80-e9fa-11e8-8bd7-0c5d2a9e1349.png)
This is what the export looks like:
![chart 6](https://user-images.githubusercontent.com/1821383/48658208-0e40f000-e9fb-11e8-9353-f0d82df77972.png)

**Comment by alexanderPolosatov** [comment]
Hi,

Thank you for the provided scenario. I have created a separate ticket in our Support Center regarding this behavior: [Wrong background color after exporting with the 'exportFromMarkup' method](https://www.devexpress.com/Support/Center/Question/Details/T692964/wrong-background-color-after-exporting-with-the-exportfrommarkup-method).
As a temporary solution, you can set the background color by using **options.backgroundColor** as shown in [this](https://codesandbox.io/s/p9lmop7rpq) example.

**Comment by jakehockey10** [comment]
@alexanderPolosatov  I appreciate you opening a ticket on my behalf, but the issue you show in the devexpress ticket is NOT the issue I showcased here.  My images show a different issue entirely than the issue showcased in the pictures you chose to attach on the devexpress ticket.  What I attempted to showcase is that the export does not include any labels for the axes in the charts.  Yes, the background color is different, but I just assumed that was by design.  The real issue is that when I export (with my code or the demo that I linked to), I don't get any labels for my charts.

Can we reopen this ticket since it is not resolved or acknowledged as is?

**Comment by alexanderPolosatov** [comment]
@jakehockey10  The color of legend labels is equal to **rgba(255,255,255,0.87)**. You can see these items in the demo because its background color equals **#363640**. You can't see these labels as a result of export because the background isn't passed to the **exportFromMarkup** method and you see a chart with a white background. The same relates to axis labels. I have attached a video where you can see what happens if you disable dark background in our demo. We will fix this issue in the context of [this](https://www.devexpress.com/Support/Center/Question/Details/T692964/wrong-background-color-after-exporting-with-the-exportfrommarkup-method) ticket in our Support Center.

[background_issue.zip](https://github.com/DevExpress/DevExtreme/files/2607974/background_issue.zip)

**Comment by jakehockey10** [comment]
I apologize for my confusion.  But the ticket you link to still has a picture representing the current state of affairs and that does not match my current state of affairs.  The labels show up fine in your image file named current (attached to the support ticket).  Mine, however, does not show the labels.  

I see what you mean by the background.  I hope we are on the same page, despite my confusion with the support ticket you created.  Thanks
