### ISSUE TITLE
Inconsistent styling: focused and selected rows have different background in data grid

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6464]
### Steps to Reproduce:

1.  Test data grid row selection
2. Test data grid row focus feature

### Results You Received:
Focused row and selected row has different styling

### Results You Expected:
Both focused row and selected row to have the same background

Is there a good reason to differentiate focused and selected rows?

### Environment Details:
DevExtreme 18.2.4

**Comment by AntonSermyazhko** [comment]
Hello,
 
The focused row and selected row are different features with different functionality.
For example, the focused row can be used to select rows. This behavior is similar to that of Windows Explorer:
![focusedrowwinexplorer](https://user-images.githubusercontent.com/29482428/50396771-03f1de80-077d-11e9-9739-0040efbf4bc0.gif)
The focused row can be used to navigate to and highlight a specific row by its key or index.
That's why the focused row has different styling.

**Comment by superole** [comment]
Just a side-note: the way they are styled now though, with both setting background-color and focus taking precedence, it is not possible to see whether the focused row is selected or not. (In win explorer focused row is outlined)

**Comment by AntonSermyazhko** [comment]
Hi, thank you for feedback.
We are planning to add this feature in one of our future releases.
