### ISSUE TITLE
Wrong popup width in Internet Explorer

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#6541]
### Steps to Reproduce:

1. Place dataGrid inside Popup (width and height of dataGrid's popup form is auto)
2. Allow popup editing in DataGrid
3. Popup width is correct in Chrome, but incorrect in Internet Explorer (tested on IE 11)

### Results You Received:

Cut off content of popup

### Results You Expected:

Fully-visible editors inside Popup

### Environment Details:
DevExtreme: 18.2.4 and older

Here is a working demo: https://jsfiddle.net/wnxj0edo/ (jsfiddle is readonly in IE). I've attached a screenshot with the issue:
![err](https://user-images.githubusercontent.com/13969777/50919342-9966c100-1453-11e9-8e81-15df3dbc0711.png)

**Comment by San4es** [comment]
Hi,

Thank you for the report. We are aware of this issue. We attempted to fix it in the context of the [T590137](https://supportcenter.devexpress.com/ticket/details/t590137/) ticket. This caused massive negative side effects.

Since this issue occurs in specific browsers (Internet Explorer and Microsoft Edge), we decided to do the following:
- revert this fix from the DevExtreme codebase;
- report this bug to the Microsoft bug tracker: [Container with flex-basis: 0 is cropped when it is placed in another container whose position style option is absolute](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15959928/);
- find workarounds for this issue set popup width (other than `auto`) and add these styles:
```css
.dx-item-content.dx-box-item-content {
    flex-basis: auto !important;
}
```

I have modified your example to demonstrate this workaround:
[https://jsfiddle.net/San4es/f8gk4326/](https://jsfiddle.net/San4es/f8gk4326/).
