### ISSUE TITLE
Grid CSS Scroll Bar with alt rows not correct

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#7001]
Grid Scroll bar is under the alternate row colors
V 18.2.6
![image](https://user-images.githubusercontent.com/30090055/53123497-3d4d8d00-3527-11e9-8f72-20889c35320a.png)

**Comment by AlisherAmonulloev** [comment]
I was unable to reproduce the issue. Below is an image illustrating how DataGrid looks when I change the color of rows and the color of the scrollbar through the Google Chrome's DevTools
![image](https://user-images.githubusercontent.com/25052481/53486147-ff0d1c00-3a98-11e9-9be6-5c52aa4f151d.png)
Please prepare a simple project illustrating the problem so that I can examine it.
