### ISSUE TITLE
Validation for selectBox with boolean value working incorrect

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7025]
### Steps to Reproduce:

1. Create a form with SelectBox
2. Set dataSource with boolean value
3. Select boolean 'false' value, validation Required is triggered

### Results You Received:

Validation Required is triggered for selected false value

### Results You Expected:

If the value selected (true or false) validation should not trigger

### Environment Details:

18.2.6, online demo: https://codepen.io/anon/pen/aXgJNV

**Comment by San4es** [comment]
@alexander-kotov-dx 

Does [this PR](https://github.com/DevExpress/DevExtreme/pull/7000) fixes this issue?

**Comment by alexander-kotov-dx** [comment]
@San4es, it is another issue. 
Regarding this case, the Required rule validation now fails if a widget has an _undefined_, _false_ or _null_ value. This logic was implemented because we have editors that operate true\false values only (dxCheckBox). In this particular case, we recommend using [Compare](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxValidator/Validation_Rules/CompareRule/) or [Custom](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxValidator/Validation_Rules/CustomRule/) validating rules 
```
validationRules: [{
    type: "custom",
    validationCallback: function(data) {
        return data.value !== undefined
    }
}]
```
