### ISSUE TITLE
Grid Filter Chrome Issue

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#7407]
When trying to mouse wheel scroll in a filter in chrome where the page also scrolls, the control closes and then scrolls the page, issue doesnt happen in fire fox.

![filterscroll_chrome_ff](https://user-images.githubusercontent.com/30090055/54838626-73ee0300-4c9f-11e9-8932-1ab5cb99ad0c.gif)

**Comment by Alyar666** [comment]
Hi @bbakermmc 

This issue is related to the existing [T724265: Scroll - The "Unable to preventDefault inside passive event listener due to target being treated as passive." error occurs on an attempt to scroll a view in Chrome ](https://www.devexpress.com/Support/Center/Question/Details/T724265/) that was fixed in the upcoming v18.2.8.
