### ISSUE TITLE
Resizing dxDataGrid does not always render newly visible rows

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#7411]
### Steps to Reproduce:

1.  Go to this codepen: https://codepen.io/anon/pen/gEZBzM
2.  Scroll the grid half-way down
3.  Click the '600' button to increase the grid's height.

### Results You Received:
Half of the visible rows are not rendered.

### Results You Expected:
When grid resizes, all visible rows should be rendered.

My current workaround is to call repaint() after the resize, but this is quite slow.

### Environment Details:
version 18.2.7

**Comment by artem-kurchenko** [comment]
Hi @pcurrivan ,

DataGrid doesn't automatically track container size changes. I suggest you use [updateDimensions](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#updateDimensions) instead of 'repaint' in such scenarios, as the repaint method re-renders the whole layout which is redundant is such cases.

**Comment by pcurrivan** [comment]
Thank you, I will use updateDimensions.
