### ISSUE TITLE
SelectBox item overlay is not visible in fullscreen

### ISSUE THREAD

**Issue by VeryBueno** [DevExpress/DevExtreme#7888]
# Bug Report

**Package versions:**

    devexteme version: 18.2
    devextreme-angular version: 18.2

**Steps to reproduce:**

https://stackblitz.com/edit/angular-nwirej

**Current behavior:**

1. Add `<dx-select-box>` to page
2. Click on dropdown, options appear.
3. Click on "fullscreen" button. The container element will go full screen.
4. While in full screen, click on dropdown again. Options are not visible.

**Expected behavior:**

Dropdown options should be visible in full screen.

This also affects other widgets that overlay on the page, such as the DateBox.

**Screenshots:**

**Comment by artem-kurchenko** [comment]
Hi @VeryBueno ,
The problem occurs because "requestFullscreen" displays a container above the "body" element while all drop-down windows are defined inside "body" by default.
You can define the onOpened event handler to move a drop-down window to a specific element:
onOpened(e) { e.component._popup.option("container", this.container.nativeElement); } 
 
Example - https://codesandbox.io/s/k0wjkjjn4v

Note that the "_popup" field is private and can be changed without any warning.

We have plans to add the capability to specify the "container" and other popup options in the widget config.
