### ISSUE TITLE
File manager that's in CTP - client side multiple questions on how it will work

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#8199]
Looked through https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileManager/BindingToFileSystem/jQuery/Light/ and the associated API documentation (https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFileManager/) but couldn't see what the selected items array and selected item will be like.

Can you elaborate or provide an example array with selected items?

Specifically:
1. Will it automatically parse the local file system from the starting root I provide in the options? i.e. if I give it `c:\` will it parse automatically each folder and sub-folder?
2. If I select folder(s), will it automatically select any files in sub-folders automatically?
3. Is there a limit how how deep the sub-folders go?
4. For each selected item, will it contain the full path?
5. How does it deal with different path structures, i.e. Windows, Linux, Mac?
6. Can I specify the specific extensions to only include for files (i.e. only .gif, .png, .jpeg, .jpg)
7. I need to take the selected files and upload them to a backend server using an existing upload control to which I can supply form fields as meta-data and the files as a multipart upload in a single API call. I'm assuming I should still be able to do that from retrieving the items data selected in the file manager and pull the paths and integrate with the form fields I send to send (i.e. job name, customer name, and the files with their paths). Does your upload control support doing this as well and / or integrate in any way with the file manager?

**Comment by CodeKarno** [comment]
Hi @genachka 

> 1. Will it automatically parse the local file system from the starting root I provide in the options? i.e. if I give it `c:\` will it parse automatically each folder and sub-folder?

For ASP.NET-based applications, you can use the server-side FileSystemProvider to connect the FileManager to the _server_ file system. See the [ASP.NET Core File Manager - Binding To File System](https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileManager/BindingToFileSystem/NetCore/Light/) demo. It illustrates how to use this class.


> 2\. If I select folder(s), will it automatically select any files in sub-folders automatically?

Folder selection works similar to Windows Explorer selection. If you use the select check box in the FileManager header, it selects all items in this folders. You can try it in one of our [online demos](https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileManager/BindingToHierarchicalStructure/NetCore/Light/). However, selection is _not_ recursive and does _not_ select items in sub-folders.


> 3\. Is there a limit how how deep the sub-folders go?

No limit.

> 4\. For each selected item, will it contain the full path?

It will contain a full path relative to the root folder.

> 5\. How does it deal with different path structures, i.e. Windows, Linux, Mac?

FileManager operates with a file system only via FileSystemProvider. This class uses standard _.NET Core_ libraries to work with file systems. Since .NET Core is cross-platform, FileSystemProvider interaction with file systems is cross-platform at the same level. 

> 6\. Can I specify the specific extensions to only include for files (i.e. only .gif, .png, .jpeg, .jpg)

Currently, FileManager does not provide this functionality. If you wish to allow uploading specific file types only, it is possible to accomplish with a separate [FileUploader](https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileUploader/Validation/NetCore/Light/).  To hide the built-in FileManager uploader, disable the [permissions.upload](https://js.devexpress.com/DevExtreme/ApiReference/UI_Widgets/dxFileManager/Configuration/permissions/#upload) option. 
If you face problems with implementation or your task is different, please submit a ticket to our Support Center: https://www.devexpress.com/ask

> 7\. I need to take the selected files and upload them to a backend server using an existing upload control to which I can supply form fields as meta-data and the files as a multipart upload in a single API call. I'm assuming I should still be able to do that from retrieving the items data selected in the file manager and pull the paths and integrate with the form fields I send to send (i.e. job name, customer name, and the files with their paths). Does your upload control support doing this as well and / or integrate in any way with the file manager?

It will be more efficient to address this scenario in [Support Center](https://www.devexpress.com/ask). Please submit a ticket and our Support Team will provide you with a proper solution. It will be helpful if you attach a test project illustrating your current implementation and describe the expected output.

**Comment by genachka** [comment]
Sounds like the initial release while a good start, is going to very limited for our use cases. Hopefully future versions add more generic support and the additional features we're looking for. :(

:( That's too bad. This is a pure Javascript (ES7+) application on the frontend via Aurelia framework.
>>Will it automatically parse the local file system from the starting root I provide in the options? i.e. if I give it c:\ will it parse automatically each folder and sub-folder?

>For ASP.NET-based applications, you can use the server-side FileSystemProvider to connect the FileManager to the server file system. See the ASP.NET Core File Manager - Binding To File System demo. It illustrates how to use this class.

That's too bad. Not going to work for our use cases. Other such controls I've used support recursive selection of any sub-folder items as well. Need a feature for it to work like your TreeList control that can select multiple levels deep.
>>2. If I select folder(s), will it automatically select any files in sub-folders automatically?

>Folder selection works similar to Windows Explorer selection. If you use the select check box in the FileManager header, it selects all items in this folders. You can try it in one of our online demos. However, selection is not recursive and does not select items in sub-folders.

:( No use of .NET here. Just a pure Javascript (ES7+) application on the frontend via Aurelia framework making RESTful API calls.
>5. How does it deal with different path structures, i.e. Windows, Linux, Mac?

>>FileManager operates with a file system only via FileSystemProvider. This class uses standard .NET Core libraries to work with file systems. Since .NET Core is cross-platform, FileSystemProvider interaction with file systems is cross-platform at the same level.

**Comment by CodeKarno** [comment]
Hi @genachka 

While we have special server-side helpers for ASP.NET Core only, it is possible to use the control with other Web API services on backend: [File Providers > Ajax](https://js.devexpress.com/DevExtreme/ApiReference/UI_Widgets/dxFileManager/File_Providers/Ajax/).
The service should return a JSON structure representing your file system structure. You can see the example of the JSON data in the data.js file from the [Binding to Hierarchical Structure](https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileManager/BindingToHierarchicalStructure/jQuery/Light/) demo.

As for the recursive selection requirement, could you please tell us more about it? 
If you need this for handling data operations recursively, such as copying or deleting a directory, the File Manager component supports this. 
If you process selection differently, please describe the entire scenario where you wanted to use File Manager. Perhaps, we can suggest another approach.
